language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: V1FblqJNQmmNtOST561zQm/E6saW/qpte/P2Q/W4+HePSStqLeEGOK0yVpysJ4fgR4MYtM59fTpEsxRkdGTDtU/xzLh0Ww/WV4/XfowDsUE2cBv6FNs3mpsynnm9lMLoL/i7UcY1EfO2hmofrlLkpo+F78akJLS31pM7qE0Uj2tEGShp763C1+4VhB8q7zR7rNQkwrsRXJylJKOOPlJvwgPsmXg2vwbwqzgKRg72f70GeolcBsC5YGL6B4a6ff0KdNboF/OGgxFXaNxaYzy7L2Ozn5WlAQNpIqXVJn65MNEUXW1h5Xr/lLNrZJrqZQDjjuWMGRcUj9oR9H0XKvjgt82jSny4lTh8CQKFv89KxUohfI0g36hKe9p5JsBSFKCh2jnrdC+ERLd2boxTkVIzeIACJnGkEzBHp6+youDZWSCIR3xaHuwCP5Nk/ewomj5OO5F3wVNTbTYUI2toZF3CTXN2pKaRjySEppfFg6Tr6xtMMq6z+QovFvzEPD0Qmv9Czue1Q+q9PTQMuM+DrZhKD7yx1YBdfPyC0B91eZtKi+zLlmi5mogJw7BEL9Ld/UgWrSdMaU9yiZ4t7+5N5qh9VkGyDXgm9JS/Q3F2udM1SAyVKhJt2pLDwkFkaoxvfTuvIsQW+ykNt/aljNMFFRPD+WVUNwgYBTEZD+manTTaU58=
  app: peaceful-spire-83083
  on:
    repo: fastlain/SurveySays
